# CI de Nível 03 - Disparo após a conclusão de um pipeline

# Nome do nosso 'pipeline'
name: 'Execução por Deploy'

# Regras de disparo (gatilhos/triggers)
# Gatilho de execução manual = workflow_dispatch
# Gatilho de execução agendada = schedule
# Gatilho de exec. a partir de outro pipe = workflow_run
 
on:
  workflow_run:
    workflows: ['Execução Manual']
    types:
      - completed

# Trabalhos/tarefas dentro do pipeline = jobs
jobs: 
  e2e-tests:

    # Máquina que o job vai executar
    runs-on: ubuntu-latest

    #condicional -if
    #`${expressao}`

    if: ${{ github.event.workflow_run.conclusion == 'success' }}



    # Passos do script de build
    steps:
      # Clone do projeto
      - uses: actions/checkout@v4

      # Instalação do Node
      - uses: actions/setup-node@v4
        with: 
          node-version: 22.x

      # Instalação do Yarn
      - name: Instalando Yarn
        run: npm install -g yarn

      # Instalação das dependências
      - name: Instalando dependências
        run: yarn

      # Instalação do Playwright
      - name: Instalando Playwright
        run: yarn playwright install

      # Executar os testes E2E
      - name: Executando Testes E2E
        run: yarn run e2e

      #Subir o relatório da execução do teste
      - uses: actions/upload-artifact@v4
        if: {{ !cancelled() }}
        with:
          name: relatorio
          path: ./playwright-report

      
